# Generated by Django 3.1.4 on 2021-04-07 05:43

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import web.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='galery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto_galery', models.FileField(blank=True, null=True, upload_to=web.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf']), web.models.file_size])),
                ('tanggal', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='berita',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('judul_berita', models.CharField(max_length=50)),
                ('foto_berita', models.FileField(blank=True, null=True, upload_to=web.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['pdf']), web.models.file_size])),
                ('isi_berita', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
