# Generated by Django 3.1.4 on 2021-04-07 10:41

import django.core.validators
from django.db import migrations, models
import web.models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_agenda', models.CharField(max_length=50)),
                ('keterangan_agenda', models.TextField()),
                ('tanggal_agenda', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='kontak',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kontak', models.CharField(max_length=50)),
                ('email_kontak', models.CharField(max_length=50)),
                ('isi_Kontak', models.TextField()),
                ('tanggal', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.AlterField(
            model_name='berita',
            name='foto_berita',
            field=models.FileField(blank=True, null=True, upload_to=web.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg']), web.models.file_size]),
        ),
        migrations.AlterField(
            model_name='galery',
            name='foto_galery',
            field=models.FileField(blank=True, null=True, upload_to=web.models._upload_path, validators=[django.core.validators.FileExtensionValidator(['jpg']), web.models.file_size]),
        ),
    ]
