# Generated by Django 3.1.4 on 2021-04-08 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0002_auto_20210407_1741'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agenda',
            name='nama_agenda',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='berita',
            name='judul_berita',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kontak',
            name='email_kontak',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='kontak',
            name='nama_kontak',
            field=models.CharField(max_length=100),
        ),
    ]
